name: Deploy Personal Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Dependencies
        run: |
          npm install -g html-minifier-terser
          npm install -g clean-css-cli
          
      - name: Build and Optimize
        run: |
          # Create dist directory
          mkdir -p dist
          
          # Copy all files
          cp -r * dist/ || true
          
          # Minify HTML files
          find dist -name "*.html" -exec html-minifier-terser --collapse-whitespace --remove-comments --remove-optional-tags --remove-redundant-attributes --remove-script-type-attributes --remove-tag-whitespace --use-short-doctype --minify-css true --minify-js true -o {} {} \;
          
          # Minify CSS
          cleancss -o dist/styles.css styles.css
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
